# Generated by Django 4.0.6 on 2022-08-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_category_options_alter_wiki_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано да/нет'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y%m%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
